### ISSUE TITLE
Dead links in the community-workflow

### ISSUE THREAD

**Issue by LukasRoeseler** [codecheckers/codecheckers.github.io#13]
There are multiple dead links in the community workflow at https://codecheck.org.uk/guide/community-workflow:
- "colophon": https://github.com/benmarwick/rrtools/blob/master/inst/templates/paper.Rmd#L105
- "see this discussion on Twitter": https://x.com/MilesMcBain/status/1263272935197782016?s=09
- https://research-compendium.science
- https://the-turing-way.netlify.com/make/make.html

**Comment by nuest** [comment]
https://research-compendium.science/ works for me.
