### ISSUE TITLE
Add Stephen's participation in UT Twente panel discussion

### ISSUE THREAD

**Issue by nuest** [codecheckers/codecheckers.github.io#8]
@sje30 Is there a recording of the event that we could add to the "News" section?

Did you share any slides or material?

**Comment by sje30** [comment]
hi Daniel, just found them at:

https://www.youtube.com/watch?v=uMeM04tE21g&t=1758s

https://openaccess.be/2021/09/20/open-science-webinars-free-and-fair-open-access/

**Comment by nuest** [comment]
The video is not online anymore, unfortunately, and the discussion was not focused on CODECHECK, so sadly it's a bit hard to spin a good story after such a long time.

I vouch to do better (and our news section does already look good..) :exclamation:
